version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-17  # Utilisation d'une image avec Maven et OpenJDK 11

jobs:
  build:
    executor: maven-executor  # Utilisation de l'exécuteur défini ci-dessus
    steps:
      - checkout  # Vérifier le code source
      - run:
          name: Run Maven tests
          command: mvn test  # Exécuter les tests unitaires avec Maven
  upload_to_codecov:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Upload to codecov
          command: mvn clean test jacoco:report
          


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload_to_codecov:
          needs: build