version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-17  # Utilisation d'une image avec Maven et OpenJDK 17

jobs:
  build:
    executor: maven-executor  # Utilisation de l'exécuteur défini ci-dessus
    steps:
      - checkout  # Vérifier le code source
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Maven tests
          command: mvn test  # Exécuter les tests unitaires avec Maven
      - run:
          name: Run CheckStyle
          command: mvn checkstyle:check
      - run:
          name: Generate CheckStyle Report
          command: mvn checkstyle:checkstyle
      - run:
          name: Run Maven coverage
          command: mvn jacoco:report
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -s target/site/jacoco -r "Gregoire-Pierrot/ceri-m1-techniques-de-test"
      - store_artifacts:
          path: target/site
          destination: reports
      - run:
          name: Calculate CheckStyle Conformity
          command: |
            ERRORS=$(grep '<error' target/checkstyle-result.xml | wc -l)
            FILES=$(grep '<file' target/checkstyle-result.xml | wc -l)
            
            if [ ! -f target/checkstyle-result.xml ]; then
              echo "Le fichier target/checkstyle-result.xml est manquant!"
              exit 1
            fi

            if [ "$FILES" -gt 0 ]; then
              PERCENTAGE=$((100 - (ERRORS * 100 / FILES)))
            else
              PERCENTAGE=100
            fi

            echo "Nombre d'erreurs: $ERRORS"
            echo "Nombre de fichiers: $FILES"
            echo "Pourcentage attendu: $PERCENTAGE%"
            echo "Checkstyle Conformity: $PERCENTAGE%"

            if grep -q "!\[Checkstyle Conformity\]" README.md; then
              sed -i "s/!\[Checkstyle Conformity\](.*)/![Checkstyle Conformity](https:\/\/img.shields.io\/badge\/Checkstyle-${PERCENTAGE}%25-brightgreen)/" README.md
            else
              echo "Aucun badge Checkstyle trouvé dans README.md."
              exit 1
            fi
      - run:
          name: Commit and Push Updated README
          command: |
            git config --global user.name "circleci[bot]"
            git config --global user.email "circleci[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update Checkstyle badge to $PERCENTAGE%"
            git push origin $(git rev-parse --abbrev-ref HEAD)
      
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master