version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-17  # Utilisation d'une image avec Maven et OpenJDK 17

jobs:
  build:
    executor: maven-executor  # Utilisation de l'exécuteur défini ci-dessus
    steps:
      - checkout  # Vérifier le code source
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Maven tests
          command: mvn test  # Exécuter les tests unitaires avec Maven
      - run:
          name: Run CheckStyle
          command: mvn checkstyle:check
      - run:
          name: Generate CheckStyle Report
          command: mvn checkstyle:checkstyle
      - run:
          name: Run Maven coverage
          command: mvn jacoco:report
      - run:
          name: Upload to codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -s target/site/jacoco -r "Gregoire-Pierrot/ceri-m1-techniques-de-test"
      - store_artifacts:
          path: target/site
          destination: reports

  generate-javadoc:
    executor: maven-executor
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: '21'
      - name: Documentation
        run: |
          mvn javadoc:javadoc
      - name: Upload javadoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs

      
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master