name : Documentation with javadoc

permissions:
    contents: write

on:
  push:
    branches:
        - master
        - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc
      - name: Upload Javadoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          name: javadoc
          path: ./target/report/apidocs